node {
  sh 'pwd'
  try {
    stage('Checkout') {
      checkout scm
    }
    stage('Environment') {
      sh 'git --version'
      sh 'npm install'
    }
  }
  catch (error) {
    throw error
  }
}
